name: build and test

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'
  PRODUCT_SLN: 'product-service'
  PRODUCT_TESTS: 'product-service/tests'

jobs:
  build-and-test-product-service:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: ${{env.PRODUCT_SLN}}
      run: dotnet restore
      
    - name: Build
      working-directory: ${{env.PRODUCT_SLN}}
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: ${{env.PRODUCT_TESTS}}
      run: dotnet test --no-restore --verbosity normal
