name: build and test

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'
  PRODUCT_SLN: '~/product-service/ES.ProductService.sln'
  PRODUCT_TESTS: '~/product-service/tests/ES.ProductService.Application.UnitTests.csproj'

jobs:
  build-and-test-product-service:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ${{env.PRODUCT_SLN}}
      
    - name: Build
      run: dotnet build ${{env.PRODUCT_SLN}}  --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ${{env.PRODUCT_TESTS}} --no-restore --verbosity normal
